unit TestUpgraderRunner;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, UpgraderRunner;

type
  // Test methods for class TUpgraderRunner

  TTestUpgraderRunner = class(TTestCase)
  strict private
    FUpgraderRunner: TUpgraderRunner;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetExistingDbVersion;
  end;

implementation

procedure TTestUpgraderRunner.SetUp;
begin
  FUpgraderRunner := TUpgraderRunner.Create;
end;

procedure TTestUpgraderRunner.TearDown;
begin
  FUpgraderRunner.Free;
  FUpgraderRunner := nil;
end;

procedure TTestUpgraderRunner.TestGetExistingDbVersion;
var
  LReturnValue: Integer;
  LDbFilePathName: string;
begin
  LDbFilePathName := '';
  LReturnValue := FUpgraderRunner.GetExistingDbVersion(LDbFilePathName);
  CheckEquals(30, LReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TTestUpgraderRunner.Suite);
end.

