unit TestDbUpgraderModules;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, DbUpgraderModules;//, System.Classes;

type
  // Test methods for class TDbUpgraderModules

  TestTDbUpgraderModules = class(TTestCase)
  strict private
    FDbUpgraderModules: TDbUpgraderModules;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestRegisterModule;
  end;

implementation

uses
  OfficeDbUpgraderModule9999,
  System.SysUtils;

procedure TestTDbUpgraderModules.SetUp;
begin
  FDbUpgraderModules := TDbUpgraderModules.Create(COfficeDbUpgraderModuleClassNamePrefix);
end;

procedure TestTDbUpgraderModules.TearDown;
begin
  FDbUpgraderModules.Free;
  FDbUpgraderModules := nil;
end;

procedure TestTDbUpgraderModules.TestRegisterModule;
begin
  try
    FDbUpgraderModules.RegisterModule(TOfficeDbUpgraderModule9999);
  except on E: Exception do
    Fail(E.Message);
  end;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTDbUpgraderModules.Suite);
end.

