unit TestDbUpgraderModules;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  DUnitX.TestFramework, DUnitX.DUnitCompatibility, DbUpgraderModules;//, System.Classes;

type
  TestTDbUpgraderModules = class(TTestCase)
  strict private
    FDbUpgraderModules: TDbUpgraderModules;
  public
    procedure SetUp; override;
    procedure TearDown; override;
//  published
    [TestCase]
    procedure TestRegisterModule;
  end;

implementation

uses
  TestModule9999,
  TestModule1111,
  System.SysUtils;

procedure TestTDbUpgraderModules.SetUp;
begin
  FDbUpgraderModules := TDbUpgraderModules.Create('TestModule');
end;

procedure TestTDbUpgraderModules.TearDown;
begin
  FDbUpgraderModules.Free;
  FDbUpgraderModules := nil;
end;

procedure TestTDbUpgraderModules.TestRegisterModule;
begin
//  try
    FDbUpgraderModules.RegisterModule(TTestModule9999);
    FDbUpgraderModules.RegisterModule(TTestModule1111);
    CheckEquals(TTestModule1111, FDbUpgraderModules[0]);
    CheckEquals(TTestModule9999, FDbUpgraderModules[1]);
//  except on E: Exception do
//    Fail(E.Message);
//  end;
end;

initialization
  // Register any test cases with the test runner
  TDUnitX.RegisterTestFixture(TestTDbUpgraderModules);
end.

